coders/pdf.c
ViewerPreferences<</PageDirection/R2L>> is inserted into a PDF file when option value is NOT "right-to-left".
It's a backport of:
https://github.com/ImageMagick/ImageMagick/commit/247be4d4c6d0c13b008bd61db21152a5f48d0e57
=> Fix pdf:page-direction flag

coders/msl.c, magick/constitute.c, magick/draw.c, magick/fx.c, magick/montage.c, magick/nt-base.c, wand/drawing-wand.c
found by cppcheck
[coders/msl.c:575] -> [coders/msl.c:555]: (warning) Either the condition 'image==(Image*)NULL' is redundant or there is possible null pointer dereference: image.
[magick/constitute.c:1078] -> [magick/constitute.c:1075]: (warning) Either the condition 'image!=(Image*)NULL' is redundant or there is possible null pointer dereference: image.
[magick/draw.c:885] -> [magick/draw.c:883]: (warning) Either the condition 'draw_info!=(DrawInfo*)NULL' is redundant or there is possible null pointer dereference: draw_info.
[magick/fx.c:3977] -> [magick/fx.c:3975]: (warning) Either the condition 'image!=(Image*)NULL' is redundant or there is possible null pointer dereference: image.
[magick/fx.c:5039] -> [magick/fx.c:5036]: (warning) Either the condition 'right_image!=(const …
=> resolve several null pointer dereferences.

coders/miff.c
Note: this is a follow-up of https://github.com/ImageMagick/ImageMagick/pull/1253/
---
When neither of those compiler macros are available, the compiler is going to spit a warning about the unused static function.
```
coders/miff.c:164:14: warning: 'AcquireCompressionMemory' defined but not used [-Wunused-function]
static void *AcquireCompressionMemory(void *context,const size_t items,
```
Fix this by making sure the static function is only defined when it's going to be used.
=> Fix compiler warning about unused function.

magick/MagickCore-config.in
This bug produces "Unknown option -config" error:
```
Unknown option -config
```
=> Remove non-existing "-config" option from pkg-config

coders/svg.c
When the svg file contains element with attribute class="" ie. empty string, the parser will end in endless loop which could led to DOS.
=> Avoid freezing when svg file contains empty class name.

coders/webp.c
Hi.
I've found some bugs in the webp coder (both decoder & encoder).
Please refer to the below for more details.
1. "Image ping" cannot extract the number of scenes correctly. When I aim to get properties of an animated webp image via “MagickPingImageBlob” function, a wand object returned from the function doesn’t contain the exact number of scenes. (MagickGetNumberImages always returns 1). So, I checked the webp decoder part, and I found the decoder only loads entire image frames when the ping flag doesn’t set. Therefore, I suggest the decoder load full frames whether a given request is ping type or not.
2. Here, the current decoder assumes the first page doesn’t have positional information. The webp library correctly provides the size of virtual its virtual canvas by parsing headers; …
=> Fix bugs (ping/encoder/dispose_method/position) in webp coder

coders/jpeg.c
This fixes incorrect data processing in libjpeg callbacks.
Fixes https://github.com/ImageMagick/ImageMagick6/issues/150
Fixes https://github.com/ImageMagick/ImageMagick6/issues/151
=> Fix incorrect client_data pointer being set in libjpeg context

magick/profile.c
Hi, I've found the memory leak when it failed to apply ICC color profile in ProfileImage function so I fixed it. I hope it will help you. Thanks for your efforts to maintain ImageMagick library.
=> Fix memory leak when it failed to apply ICC color profile

magick/string.c
Same as https://github.com/ImageMagick/ImageMagick/pull/3858
=> fix memory corruption in ConcatenateStringInfo

magick/visual-effects.c
I noticed that the fix for [CVE-2021-20244](https://nvd.nist.gov/vuln/detail/CVE-2021-20244) in https://github.com/ImageMagick/ImageMagick/commit/329dd528ab79531d884c0ba131e97d43f872ab5d wasn't backported to IM6.
Please note that I have very little clue of C programming. It compiles though and I think the fix is not very complex.
=> Backport fix for CVE-2021-20244

magick/log.c, magick/log.h, magick/pixel-accessor.h
We have an error building 'lebiniou' on FreeBSD (and maybe other platform). 'lebiniou' uses -Werror flag and raises errors in ImageMagick6:
`error: 'const' type qualifier on return type has no effect [-Werror,-Wignored-qualifiers]`
Removing theses `const` allows building 'lebiniou' (and other software using these files with -Werror flag).
FreeBSD patch: https://github.com/freebsd/freebsd-ports/commit/06ba562579f8b627b7bb8fdafc8a3ad422577648
cc @oliv3
=> Fix build with -Werror

.github/workflows/main.yml
Adds CI for mingw-w64 using the awesome [msys2 action](https://github.com/msys2/setup-msys2). I adapted the build configuration and patches from upstream msys2 [mingw-w64-imagemagick](https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-imagemagick).
=> Test with mingw-w64 using MSYS2 CI

coders/dib.c, coders/djvu.c, coders/icon.c
These fix various redefinition warnings in mingw. The patches are imported from ImageMagick 7 repository without any significant changes. The changes are local to the corresponding functions.
=> Fix various redefinition warnings in mingw

Makefile.in, coders/Makefile.am, coders/url.c
This feature was enabled for Windows platform but disabled for mingw toolchain in 97196e70a7b3274ef45ada1a01f39637f9f829bf commit.
This fixes the following error with magick command in mingw:
```
$ identify https://imagemagick.org/image/wizard.png
identify.exe: unable to create temporary file '//imagemagick.org/image/wizard.png': No such file or directory @ error/delegate.c/InvokeDelegate/1950.
```
=> coders: Enable opening https files in mingw

magick/resample.c
This fixes a build regression that was introduced in f560fc2444497f62c9b50cf6314f31fd148b381e.
=> Restore the missing bracket

coders/jpeg.c, magick/memory.c
Avoids the error "Backing store not supported" when converting some jpeg (progressive in my case) on Windows (x86_64-w64-mingw32-gcc).
First, the initial value of max_memory_request in GetMaxMemoryRequest is inconsistent with the MagickMin return value. This was already fixed on ImageMagick 7:
- ImageMagick/ImageMagick@2f442f7f05d02dc4d0a0399c32c07c1f47fc3841
- ImageMagick/ImageMagick@6ccb83b8ad7e4532547ca738774a1aa74ff3b076
- ImageMagick/ImageMagick@28637d210be357dc11e59776864c3dc2ac52a927
I have not understood why MAGICK_SSIZE_MAX is preferred over MAGICK_SIZE_MAX.
Second, the comparison in coders/jpeg.c always returned true because neither ~0ULL nor MAGICK_SSIZE_MAX equals ~0UL on Windows when compiled with MinGW-w64, resulting in an invalid max memory size configuration in the jpeg …
=> Fix the max memory request initial value in memory.c and comparison in jpeg.c

PerlMagick/quantum/quantum.xs.in
Version 7.1.1.16 is OK
Version  6.9.12-93 was OK
Version  6.9.12-94 is broken
Trivial typo fix 
See 0304430e4c91fe0af11365bb46c15b182c2fced6
=> fix type cast

configure.ac
There are two problems with the check:
1) The 'unknown' case has a problem which is rejected by stricter C compilers because it has -Wimplicit-int and -Wimplicit-function-declaration warnings. Fix that.
2) For the 'other' case, we were using the value of ac_cv_sys_file_offset_bits for -D_FILE_OFFSET_BITS to pass down into the Perl module build, but autoconf-2.72 drops the use of ac_cv_sys_file_offset_bits in cf09f48841b66fe76f606dd6018bb3a93242a7c9, so this ends up defining '-D_FILE_OFFSET_BITS=' which then breaks the build.
I've added a hack for 2) to preserve the old behavior.
=> configure.ac: fixup LFS check for autoconf-2.72

coders/dng.c
Build failure on Fedora 37 and RHEL 9 (libRaw 0.20.2)
Also on https://github.com/ImageMagick/ImageMagick/pull/6989
=> fix error: 'libraw_data_t' has no member named 'rawparams'

configure
See below for output of running `configure`. I saw the unusual `command not found` errors. I looked at the lines indicated and discovered some odd Unicode characters. I replaced the octal characters `\357\277\274` (in hex: `\xEF\xBF\xBC`), with spaces in my local copy of `configure`, and ran it again. This seemed to resolve the problem.
From my limited exploration of where these characters came from, it looks like they were introduced in commit [119eb49](https://github.com/ImageMagick/ImageMagick6/commit/119eb49c9fb31c08b2fb260b124b593fca436e85) into lines 31599 and 31600 (as they were back then).
@urban-warrior 
```
-------------------------------------------------------------
checking for JBIG...
checking for jbig.h... yes
checking for jbg_dec_init in -ljbig... yes
checking if JBIG …
```
=> delete stray incorrect Unicode characters

coders/tiff.c
Fix missing 'tiff:endian' image property
`HAVE_TIFFISBIGENDIAN` macro was removed in
d0b6b4815e0c2ac77ea6e5dc14f67f425c0cfc47, but the macro was still used for a conditional block in `tiff.c` responsible for setting the `tiff:endian` image property. The macro was never set, essentially disabling this functionality.
We can safely remove the conditional compilation and assume `TIFFIsBigEndian` is always available: we require at least libtiff 4.0.0, while `TIFFIsBigEndian` was added in 3.7.0.
=> Fix missing 'tiff:endian' image property
